BASE_URL = 'https://stellarburgers.nomoreparties.site/api'
REGISTER_USER_URL = f'{BASE_URL}/auth/register'
LOGIN_URL = f'{BASE_URL}/auth/login'
USER_URL = f'{BASE_URL}/auth/user'
ORDER_URL = f'{BASE_URL}/orders'